-- Friends could not always find each other by name.
--
-- search_players() required p.onboarded = true, but a player can carry a real
-- chosen username without that flag ever being set — an email sign-up takes its
-- name straight from the form, and anyone who did not click all the way through
-- the extra setup screen stays onboarded = false. Meanwhile the browse list,
-- all_players(), only hides the autogenerated 'player_xxxxxxxx' names and shows
-- everyone else. So a real player showed up when you browsed but vanished when a
-- friend searched their name.
--
-- This makes the two agree: anyone with a real (non-placeholder) username is
-- findable, and only the autogenerated names stay hidden.

create or replace function public.search_players(query text)
returns table (id uuid, name text, character_id text, level integer)
language plpgsql stable security definer set search_path = public as $$
declare term text;
begin
  if auth.uid() is null then raise exception 'Sign in to search for players'; end if;
  term := trim(query);
  if char_length(term) < 2 then return; end if;
  -- Escape LIKE wildcards so a search for "100%" cannot match everything.
  term := replace(replace(replace(term, '\', '\\'), '%', '\%'), '_', '\_');
  return query
    select p.user_id, p.display_name, p.selected_character, p.current_level
    from player_profiles p
    where p.user_id <> auth.uid()
      and p.display_name !~ '^player_[0-9a-f]{8}$'
      and p.display_name ilike '%' || term || '%' escape '\'
    order by lower(p.display_name) = lower(trim(query)) desc, p.display_name
    limit 12;
end; $$;

revoke execute on function public.search_players(text) from anon, public;
grant execute on function public.search_players(text) to authenticated;
