-- Players fill in a setup screen the first time they sign in. Until they
-- finish it they have no real username, so nobody should be able to find them.

alter table public.player_profiles
  add column onboarded boolean not null default false;

-- Anyone already carrying a real username counts as set up. The signup trigger
-- hands out 'player_<8 hex>' names, and those are the unfinished ones.
update public.player_profiles
set onboarded = true
where display_name !~ '^player_[0-9a-f]{8}$';

-- The board is for players who finished setting up AND actually did something.
drop view if exists public.safe_leaderboard;
create view public.safe_leaderboard as
select display_name, total_score as score, current_level as level,
  dense_rank() over (order by total_score desc) as rank
from public.player_profiles
where onboarded and total_score > 0;
grant select on public.safe_leaderboard to anon, authenticated;

-- Search only finds finished accounts, so half-made ones with an autogenerated
-- name never show up in the friends list. Public fields only, as before:
-- never real_name, birthday, country, or anything from auth.users.
create or replace function public.search_players(query text)
returns table (id uuid, name text, character_id text, level integer)
language plpgsql stable security definer set search_path = public as $$
declare term text;
begin
  if auth.uid() is null then raise exception 'Sign in to search for players'; end if;
  term := trim(query);
  if char_length(term) < 2 then return; end if;
  -- Escape LIKE wildcards so a search for "100%" cannot match everything.
  term := replace(replace(replace(term, '\', '\\'), '%', '\%'), '_', '\_');
  return query
    select p.user_id, p.display_name, p.selected_character, p.current_level
    from player_profiles p
    where p.user_id <> auth.uid()
      and p.onboarded
      and p.display_name ilike '%' || term || '%' escape '\'
    order by lower(p.display_name) = lower(trim(query)) desc, p.display_name
    limit 12;
end; $$;
revoke execute on function public.search_players(text) from anon, public;
grant execute on function public.search_players(text) to authenticated;
